In [1]:
import pandas as pd
import pickle

In [2]:
with open("/Users/evro/Documents/code/python/fetch/data/validated/receipts.pkl", "rb") as f:
    receipts = pickle.load(f)

In [3]:
################################################
################################################
################################################
################################################
# RECEIPT ITEM DATA #
################################################
################################################
################################################
################################################

In [4]:
## Original JSON files are not formatted ###
## Formatted with process_date.py ##
## Loading newly formatted data ##
with open("/Users/evro/Documents/code/python/fetch/data/cleaned/cleaned_receipt_items.json") as f:
    receipt_item_data = pd.read_json(f)
receipt_items = pd.DataFrame(receipt_item_data)

In [5]:
receipt_items.head()

,receipt_id,brand_code,barcode,quantity_purchased,final_price,item_price,price_after_coupon,points_earned,points_payer_id,needs_fetch_review,...,partner_item_id,points_not_awarded_reason,rewards_group,rewards_product_partner_id,target_price,prevent_target_gap_points,competitor_rewards_group,competitive_product,discounted_item_price,deleted
0,5ff1e1eb0a720f0523000575,,4011,5,26.0,26.0,0.0,0.0,,False,...,1,,,,0,True,,0,0.0,False
1,5ff1e1bb0a720f052300056b,,4011,1,1.0,1.0,0.0,0.0,,False,...,1,,,,0,False,,0,0.0,False
2,5ff1e1bb0a720f052300056b,,028400642255,1,10.0,10.0,0.0,0.0,5332f5fbe4b03c9a25efd0ba,True,...,2,Action not allowed for user and CPG,DORITOS SPICY SWEET CHILI SINGLE SERVE,5332f5fbe4b03c9a25efd0ba,0,True,,0,0.0,False
3,5ff1e1f10a720f052300057a,,,0,0.0,0.0,0.0,0.0,,False,...,1,,,,0,True,,0,0.0,False
4,5ff1e1ee0a7214ada100056f,,4011,4,28.0,28.0,0.0,0.0,,False,...,1,,,,0,True,,0,0.0,False

In [6]:
######################## RECEIPT ITEMS DATA NORMALIZE & CLEANING ########################

In [7]:
receipt_item_data.dtypes

receipt_id                                 object
brand_code                                 object
barcode                                    object
quantity_purchased                          int64
final_price                               float64
item_price                                float64
price_after_coupon                        float64
points_earned                             float64
points_payer_id                            object
needs_fetch_review                           bool
needs_fetch_review_reason                  object
description                                object
original_receipt_item_text                 object
metabrite_campaign_id                      object
original_meta_brite_barcode                object
original_meta_brite_description            object
original_final_price                        int64
original_meta_brite_item_price              int64
original_meta_brite_quantity_purchased      int64
user_flagged_barcode                       object
user_flagged_description                   object
user_flagged_new_item                        bool
user_flagged_price                        float64
user_flagged_quantity                       int64
item_number                                object
partner_item_id                             int64
points_not_awarded_reason                  object
rewards_group                              object
rewards_product_partner_id                 object
target_price                                int64
prevent_target_gap_points                    bool
competitor_rewards_group                   object
competitive_product                         int64
discounted_item_price                     float64
deleted                                      bool
dtype: object

In [8]:
receipt_item_data = receipt_item_data.astype({col: "string" for col in receipt_item_data.select_dtypes(include=["object"]).columns})

In [9]:
receipt_item_data.dtypes

receipt_id                                string[python]
brand_code                                string[python]
barcode                                   string[python]
quantity_purchased                                 int64
final_price                                      float64
item_price                                       float64
price_after_coupon                               float64
points_earned                                    float64
points_payer_id                           string[python]
needs_fetch_review                                  bool
needs_fetch_review_reason                 string[python]
description                               string[python]
original_receipt_item_text                string[python]
metabrite_campaign_id                     string[python]
original_meta_brite_barcode               string[python]
original_meta_brite_description           string[python]
original_final_price                               int64
original_meta_brite_item_price                     int64
original_meta_brite_quantity_purchased             int64
user_flagged_barcode                      string[python]
user_flagged_description                  string[python]
user_flagged_new_item                               bool
user_flagged_price                               float64
user_flagged_quantity                              int64
item_number                               string[python]
partner_item_id                                    int64
points_not_awarded_reason                 string[python]
rewards_group                             string[python]
rewards_product_partner_id                string[python]
target_price                                       int64
prevent_target_gap_points                           bool
competitor_rewards_group                  string[python]
competitive_product                                int64
discounted_item_price                            float64
deleted                                             bool
dtype: object

In [10]:
receipt_item_data.head()

,receipt_id,brand_code,barcode,quantity_purchased,final_price,item_price,price_after_coupon,points_earned,points_payer_id,needs_fetch_review,...,partner_item_id,points_not_awarded_reason,rewards_group,rewards_product_partner_id,target_price,prevent_target_gap_points,competitor_rewards_group,competitive_product,discounted_item_price,deleted
0,5ff1e1eb0a720f0523000575,,4011,5,26.0,26.0,0.0,0.0,,False,...,1,,,,0,True,,0,0.0,False
1,5ff1e1bb0a720f052300056b,,4011,1,1.0,1.0,0.0,0.0,,False,...,1,,,,0,False,,0,0.0,False
2,5ff1e1bb0a720f052300056b,,028400642255,1,10.0,10.0,0.0,0.0,5332f5fbe4b03c9a25efd0ba,True,...,2,Action not allowed for user and CPG,DORITOS SPICY SWEET CHILI SINGLE SERVE,5332f5fbe4b03c9a25efd0ba,0,True,,0,0.0,False
3,5ff1e1f10a720f052300057a,,,0,0.0,0.0,0.0,0.0,,False,...,1,,,,0,True,,0,0.0,False
4,5ff1e1ee0a7214ada100056f,,4011,4,28.0,28.0,0.0,0.0,,False,...,1,,,,0,True,,0,0.0,False

In [11]:
receipt_item_data.isnull().sum()

receipt_id                                0
brand_code                                0
barcode                                   0
quantity_purchased                        0
final_price                               0
item_price                                0
price_after_coupon                        0
points_earned                             0
points_payer_id                           0
needs_fetch_review                        0
needs_fetch_review_reason                 0
description                               0
original_receipt_item_text                0
metabrite_campaign_id                     0
original_meta_brite_barcode               0
original_meta_brite_description           0
original_final_price                      0
original_meta_brite_item_price            0
original_meta_brite_quantity_purchased    0
user_flagged_barcode                      0
user_flagged_description                  0
user_flagged_new_item                     0
user_flagged_price                        0
user_flagged_quantity                     0
item_number                               0
partner_item_id                           0
points_not_awarded_reason                 0
rewards_group                             0
rewards_product_partner_id                0
target_price                              0
prevent_target_gap_points                 0
competitor_rewards_group                  0
competitive_product                       0
discounted_item_price                     0
deleted                                   0
dtype: int64

In [12]:
# convert blank strings to null
receipt_item_data.replace("", pd.NA, inplace=True)

In [13]:
receipt_item_data.isnull().sum()

receipt_id                                   0
brand_code                                4341
barcode                                   3851
quantity_purchased                           0
final_price                                  0
item_price                                   0
price_after_coupon                           0
points_earned                                0
points_payer_id                           5674
needs_fetch_review                           0
needs_fetch_review_reason                 6722
description                                381
original_receipt_item_text                1181
metabrite_campaign_id                     6078
original_meta_brite_barcode               6917
original_meta_brite_description           6931
original_final_price                         0
original_meta_brite_item_price               0
original_meta_brite_quantity_purchased       0
user_flagged_barcode                      6604
user_flagged_description                  6787
user_flagged_new_item                        0
user_flagged_price                           0
user_flagged_quantity                        0
item_number                               6788
partner_item_id                              0
points_not_awarded_reason                 6601
rewards_group                             5210
rewards_product_partner_id                4672
target_price                                 0
prevent_target_gap_points                    0
competitor_rewards_group                  6666
competitive_product                          0
discounted_item_price                        0
deleted                                      0
dtype: int64

In [14]:
boolean_cols = ["needs_fetch_review", "prevent_target_gap_points", "deleted"]
receipt_items[boolean_cols] = receipt_items[boolean_cols].astype("boolean")

In [15]:
receipt_item_data['points_earned'] = receipt_item_data['points_earned'].astype("int")

In [16]:
float_cols = ["original_final_price", "original_meta_brite_item_price", "user_flagged_price", "target_price"]
receipt_item_data[float_cols] = receipt_item_data[float_cols].astype("float")

In [17]:
receipt_item_data.dtypes

receipt_id                                string[python]
brand_code                                string[python]
barcode                                   string[python]
quantity_purchased                                 int64
final_price                                      float64
item_price                                       float64
price_after_coupon                               float64
points_earned                                      int64
points_payer_id                           string[python]
needs_fetch_review                                  bool
needs_fetch_review_reason                 string[python]
description                               string[python]
original_receipt_item_text                string[python]
metabrite_campaign_id                     string[python]
original_meta_brite_barcode               string[python]
original_meta_brite_description           string[python]
original_final_price                             float64
original_meta_brite_item_price                   float64
original_meta_brite_quantity_purchased             int64
user_flagged_barcode                      string[python]
user_flagged_description                  string[python]
user_flagged_new_item                               bool
user_flagged_price                               float64
user_flagged_quantity                              int64
item_number                               string[python]
partner_item_id                                    int64
points_not_awarded_reason                 string[python]
rewards_group                             string[python]
rewards_product_partner_id                string[python]
target_price                                     float64
prevent_target_gap_points                           bool
competitor_rewards_group                  string[python]
competitive_product                                int64
discounted_item_price                            float64
deleted                                             bool
dtype: object

In [18]:
receipt_item_data.head()

,receipt_id,brand_code,barcode,quantity_purchased,final_price,item_price,price_after_coupon,points_earned,points_payer_id,needs_fetch_review,...,partner_item_id,points_not_awarded_reason,rewards_group,rewards_product_partner_id,target_price,prevent_target_gap_points,competitor_rewards_group,competitive_product,discounted_item_price,deleted
0,5ff1e1eb0a720f0523000575,<NA>,4011,5,26.0,26.0,0.0,0,<NA>,False,...,1,<NA>,<NA>,<NA>,0.0,True,<NA>,0,0.0,False
1,5ff1e1bb0a720f052300056b,<NA>,4011,1,1.0,1.0,0.0,0,<NA>,False,...,1,<NA>,<NA>,<NA>,0.0,False,<NA>,0,0.0,False
2,5ff1e1bb0a720f052300056b,<NA>,028400642255,1,10.0,10.0,0.0,0,5332f5fbe4b03c9a25efd0ba,True,...,2,Action not allowed for user and CPG,DORITOS SPICY SWEET CHILI SINGLE SERVE,5332f5fbe4b03c9a25efd0ba,0.0,True,<NA>,0,0.0,False
3,5ff1e1f10a720f052300057a,<NA>,<NA>,0,0.0,0.0,0.0,0,<NA>,False,...,1,<NA>,<NA>,<NA>,0.0,True,<NA>,0,0.0,False
4,5ff1e1ee0a7214ada100056f,<NA>,4011,4,28.0,28.0,0.0,0,<NA>,False,...,1,<NA>,<NA>,<NA>,0.0,True,<NA>,0,0.0,False

In [19]:
######################## VALIDATE RECEIPT ITEM DATA ########################

In [20]:
receipt_items["rewards_group"].value_counts()

rewards_group
                                                                    5210
BEN AND JERRYS ICE CREAM                                             181
HUGGIES ONE AND DONE SIMPLY CLEAN BABY WIPES 200 COUNT OR LARGER      92
MILLER LITE 24 PACK                                                   90
KNORR SIDES                                                           87
                                                                    ...
COTTONELLE ULTRA CLEANCARE BATH TISSUE                                 1
GERBER GRADUATES                                                       1
DORITOS RANCHERITOS SINGLE SERVE                                       1
DORITOS COOL RANCH MULTI SERVE                                         1
TOTINO'S PARTY PIZZA - SINGLE PACK                                     1
Name: count, Length: 183, dtype: int64

In [21]:
receipt_items["rewards_product_partner_id"].value_counts()

rewards_product_partner_id
                            4672
559c2234e4b06aca36af13c6     878
5332f5f6e4b03c9a25efd0b4     315
5332f5fbe4b03c9a25efd0ba     243
550b2565e4b001d5e9e4146f     202
5332f5f3e4b03c9a25efd0ae     181
5e7cf838f221c312e698a628     157
5e825d64f221c312e698a62a     124
5332f709e4b03c9a25efd0f1      92
5a734034e4b0d58f376be874      31
5eebc5412455c97a877ef382      24
5d9b4f591dda2c6225a284aa       9
5fb6b608be37ce522e165cb9       5
53e10d6368abd3c7065097cc       3
5f036cedac99f02d72388690       3
5f58fa84be37ce21f1287c0f       1
5ffdb69ebe37ce746df1192a       1
Name: count, dtype: int64

In [22]:
receipt_items["points_payer_id"].value_counts()

points_payer_id
                            5674
559c2234e4b06aca36af13c6     331
5332f5f6e4b03c9a25efd0b4     281
5332f5fbe4b03c9a25efd0ba     230
550b2565e4b001d5e9e4146f     190
5332f709e4b03c9a25efd0f1      90
5332f5f3e4b03c9a25efd0ae      56
5a734034e4b0d58f376be874      31
5e825d64f221c312e698a62a      25
5eebc5412455c97a877ef382      24
53e10d6368abd3c7065097cc       3
5f036cedac99f02d72388690       2
5fb6b608be37ce522e165cb9       1
5f58fa84be37ce21f1287c0f       1
5e7cf838f221c312e698a628       1
5ffdb69ebe37ce746df1192a       1
Name: count, dtype: int64

In [23]:
receipt_items["competitor_rewards_group"].value_counts()

competitor_rewards_group
                                                   6666
OSCAR MAYER SAUSAGE LINK                             43
MAXWELL HOUSE GROUND COFFEE                          36
A.1. DRY RUB                                         29
OSCAR MAYER BACON                                    24
TACO BELL TACO SHELLS                                21
LIPTON TEA                                           20
CAPRI SUN BEVERAGE DRINK                             13
T.G.I. FRIDAY'S FROZEN APPETIZER                     13
SMART ONES                                           11
FOOD NETWORK KITCHEN INSPIRATIONS COOKING SAUCE      10
CLASSICO SAUCE                                        9
PLANTERS PISTACHIOS                                   6
ATHENOS PITA CHIPS                                    5
OSCAR MAYER LUNCH MEAT                                4
SHAKE 'N BAKE SEASONED COATING MIX                    3
BAKER'S CHOCOLATE                                     3
CAPRI SUN ROARIN' WATERS BEVERAGE DRINK               3
BEN AND JERRYS ICE CREAM                              3
DIET PEPSI 12 OZ 24+ COUNT                            3
PEPSI 12 OZ 24+ COUNT                                 3
GEVALIA KAFFE KEURIG COFFEE PODS                      2
VELVEETA CHEESE - SAUCE                               2
PEPSI 20 OZ                                           2
SARGENTO RICOTTA CHEESE                               1
CLAUSSEN PICKLES                                      1
ORE-IDA FROZEN POTATOES                               1
O THAT'S GOOD - SIDES                                 1
ATHENOS HUMMUS                                        1
LEA & PERRINS MARINADE - BOTTLE                       1
DEVOUR FROZEN ENTREE                                  1
Name: count, dtype: int64

In [24]:
receipt_items["prevent_target_gap_points"].value_counts()

prevent_target_gap_points
False    6583
True      358
Name: count, dtype: Int64

In [25]:
receipt_items["brand_code"].value_counts()

brand_code
                  4341
HY-VEE             291
BEN AND JERRYS     180
PEPSI               93
KROGER              89
                  ...
PACIFIC FOODS        1
EGGO                 1
GRIMMWAY FARMS       1
LA BANDERITA         1
VIVA                 1
Name: count, Length: 228, dtype: int64

In [26]:
receipt_items["needs_fetch_review"].value_counts()

needs_fetch_review
False    6722
True      219
Name: count, dtype: Int64

In [27]:
receipt_items["metabrite_campaign_id"].value_counts()

metabrite_campaign_id
                                                               6078
BEN AND JERRYS ICE CREAM                                        180
KLEENEX TRUSTED CARE FACIAL TISSUES 120 - 179 COUNT, 8 PACK      87
PEPSI 12 OZ 12 PACK                                              81
DORITOS NACHO CHEESE MULTI SERVE                                 75
                                                               ...
DORITOS COOL RANCH MULTI SERVE                                    1
DORITOS RANCHERITOS SINGLE SERVE                                  1
GERBER GRADUATES                                                  1
TACO BELL SALSA & SAUCE                                           1
VIVA MULTI SURFACE CLOTH PAPER TOWEL                              1
Name: count, Length: 76, dtype: int64

In [28]:
receipt_items["user_flagged_new_item"].value_counts()

user_flagged_new_item
False    6618
True      323
Name: count, dtype: int64

In [29]:
receipt_item_data.head()

,receipt_id,brand_code,barcode,quantity_purchased,final_price,item_price,price_after_coupon,points_earned,points_payer_id,needs_fetch_review,...,partner_item_id,points_not_awarded_reason,rewards_group,rewards_product_partner_id,target_price,prevent_target_gap_points,competitor_rewards_group,competitive_product,discounted_item_price,deleted
0,5ff1e1eb0a720f0523000575,<NA>,4011,5,26.0,26.0,0.0,0,<NA>,False,...,1,<NA>,<NA>,<NA>,0.0,True,<NA>,0,0.0,False
1,5ff1e1bb0a720f052300056b,<NA>,4011,1,1.0,1.0,0.0,0,<NA>,False,...,1,<NA>,<NA>,<NA>,0.0,False,<NA>,0,0.0,False
2,5ff1e1bb0a720f052300056b,<NA>,028400642255,1,10.0,10.0,0.0,0,5332f5fbe4b03c9a25efd0ba,True,...,2,Action not allowed for user and CPG,DORITOS SPICY SWEET CHILI SINGLE SERVE,5332f5fbe4b03c9a25efd0ba,0.0,True,<NA>,0,0.0,False
3,5ff1e1f10a720f052300057a,<NA>,<NA>,0,0.0,0.0,0.0,0,<NA>,False,...,1,<NA>,<NA>,<NA>,0.0,True,<NA>,0,0.0,False
4,5ff1e1ee0a7214ada100056f,<NA>,4011,4,28.0,28.0,0.0,0,<NA>,False,...,1,<NA>,<NA>,<NA>,0.0,True,<NA>,0,0.0,False

In [30]:
######################## RECEIPT ITEM DATA ISSUES ########################

In [31]:
# Find dup receipt items
receipt_items[receipt_items.duplicated(subset=["receipt_id", "barcode", "item_price", "quantity_purchased"], keep=False)]

,receipt_id,brand_code,barcode,quantity_purchased,final_price,item_price,price_after_coupon,points_earned,points_payer_id,needs_fetch_review,...,partner_item_id,points_not_awarded_reason,rewards_group,rewards_product_partner_id,target_price,prevent_target_gap_points,competitor_rewards_group,competitive_product,discounted_item_price,deleted
14,5ff1e1b60a7214ada100055c,,034100573065,1,29.00,29.00,0.0,870.0,5332f709e4b03c9a25efd0f1,False,...,1,,MILLER LITE 24 PACK,5332f709e4b03c9a25efd0f1,77,False,,0,0.0,False
15,5ff1e1b60a7214ada100055c,,034100573065,1,29.00,29.00,0.0,870.0,5332f709e4b03c9a25efd0f1,False,...,2,,MILLER LITE 24 PACK,5332f709e4b03c9a25efd0f1,77,False,,0,0.0,False
16,5ff1e1b60a7214ada100055c,,034100573065,1,29.00,29.00,0.0,870.0,5332f709e4b03c9a25efd0f1,False,...,3,,MILLER LITE 24 PACK,5332f709e4b03c9a25efd0f1,77,False,,0,0.0,False
17,5ff1e1b60a7214ada100055c,,034100573065,1,29.00,29.00,0.0,870.0,5332f709e4b03c9a25efd0f1,False,...,4,,MILLER LITE 24 PACK,5332f709e4b03c9a25efd0f1,77,False,,0,0.0,False
18,5ff1e1b60a7214ada100055c,,034100573065,1,29.00,29.00,0.0,870.0,5332f709e4b03c9a25efd0f1,False,...,5,,MILLER LITE 24 PACK,5332f709e4b03c9a25efd0f1,77,False,,0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6835,602402750a720f05a800016f,,043000048528,1,9.99,9.99,0.0,0.0,,False,...,1,,DUNCAN HINES CAKE MIX,5e825d64f221c312e698a62a,0,False,,1,0.0,False
6836,602402750a720f05a800016f,,043000048528,1,9.99,9.99,0.0,0.0,,False,...,2,,DUNCAN HINES CAKE MIX,5e825d64f221c312e698a62a,0,False,,1,0.0,False
6837,602402750a720f05a800016f,,043000048528,1,9.99,9.99,0.0,0.0,,False,...,3,,DUNCAN HINES CAKE MIX,5e825d64f221c312e698a62a,0,False,,1,0.0,False
6838,602402750a720f05a800016f,,043000048528,1,9.99,9.99,0.0,0.0,,False,...,4,,DUNCAN HINES CAKE MIX,5e825d64f221c312e698a62a,0,False,,1,0.0,False
6839,602402750a720f05a800016f,,043000048528,1,9.99,9.99,0.0,0.0,,False,...,5,,DUNCAN HINES CAKE MIX,5e825d64f221c312e698a62a,0,False,,1,0.0,False

In [32]:
# Are there items without receipts?
receipt_items[~receipt_items["receipt_id"].isin(receipts["receipt_id"])]

Empty DataFrame
Columns: [receipt_id, brand_code, barcode, quantity_purchased, final_price, item_price, price_after_coupon, points_earned, points_payer_id, needs_fetch_review, needs_fetch_review_reason, description, original_receipt_item_text, metabrite_campaign_id, original_meta_brite_barcode, original_meta_brite_description, original_final_price, original_meta_brite_item_price, original_meta_brite_quantity_purchased, user_flagged_barcode, user_flagged_description, user_flagged_new_item, user_flagged_price, user_flagged_quantity, item_number, partner_item_id, points_not_awarded_reason, rewards_group, rewards_product_partner_id, target_price, prevent_target_gap_points, competitor_rewards_group, competitive_product, discounted_item_price, deleted]
Index: []

[0 rows x 35 columns]

In [33]:
# Which receipt items need fetch review?
receipt_items[receipt_items["needs_fetch_review"] == True]

,receipt_id,brand_code,barcode,quantity_purchased,final_price,item_price,price_after_coupon,points_earned,points_payer_id,needs_fetch_review,...,partner_item_id,points_not_awarded_reason,rewards_group,rewards_product_partner_id,target_price,prevent_target_gap_points,competitor_rewards_group,competitive_product,discounted_item_price,deleted
2,5ff1e1bb0a720f052300056b,,028400642255,1,10.00,10.00,0.0,0.0,5332f5fbe4b03c9a25efd0ba,True,...,2,Action not allowed for user and CPG,DORITOS SPICY SWEET CHILI SINGLE SERVE,5332f5fbe4b03c9a25efd0ba,0,True,,0,0.0,False
6,5ff1e1d20a7214ada1000561,,1234,3,2.56,2.56,0.0,0.0,,True,...,2,,,,0,True,,0,0.0,False
13,5ff1e1a10a720f0523000568,,013562300631,5,50.00,50.00,0.0,0.0,5332f5f3e4b03c9a25efd0ae,True,...,1,Action not allowed for user and CPG,ANNIE'S HOMEGROWN MULTI-SERVING MAC & CHEESE,5332f5f3e4b03c9a25efd0ae,0,False,,0,50.0,False
25,5f9c74f70a7214ad07000037,,,0,0.00,0.00,0.0,0.0,,True,...,2,,,,0,True,,0,0.0,False
26,5f9c74f70a7214ad07000037,,,0,0.00,0.00,0.0,0.0,,True,...,3,,,,0,True,,0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6769,5fb2da580a7214ad89000114,,,0,0.00,0.00,0.0,0.0,,True,...,11,,,,0,True,,0,0.0,False
6779,601c68b50a720f05f40002c8,,1234,0,0.00,0.00,0.0,0.0,,True,...,2,,,,0,True,,0,0.0,False
6816,602299b40a720f05a80000bc,,1234,0,0.00,0.00,0.0,0.0,,True,...,2,,,,0,True,,0,0.0,False
6845,6025386a0a7214d8e9000241,,1234,0,0.00,0.00,0.0,0.0,,True,...,2,,,,0,True,,0,0.0,False
6850,602558a90a720f05a8000240,,1234,3,2.56,2.56,0.0,0.0,,True,...,2,,,,0,True,,0,0.0,False

In [34]:
# Duplicate receipt items that have the same receipt ID and barcode.
# This could indicate duplicate product entries under the same receipt, which might be a data integrity issue.
receipt_items[receipt_items.duplicated(subset=["receipt_id", "barcode"], keep=False)]

,receipt_id,brand_code,barcode,quantity_purchased,final_price,item_price,price_after_coupon,points_earned,points_payer_id,needs_fetch_review,...,partner_item_id,points_not_awarded_reason,rewards_group,rewards_product_partner_id,target_price,prevent_target_gap_points,competitor_rewards_group,competitive_product,discounted_item_price,deleted
14,5ff1e1b60a7214ada100055c,,034100573065,1,29.00,29.00,0.0,870.0,5332f709e4b03c9a25efd0f1,False,...,1,,MILLER LITE 24 PACK,5332f709e4b03c9a25efd0f1,77,False,,0,0.0,False
15,5ff1e1b60a7214ada100055c,,034100573065,1,29.00,29.00,0.0,870.0,5332f709e4b03c9a25efd0f1,False,...,2,,MILLER LITE 24 PACK,5332f709e4b03c9a25efd0f1,77,False,,0,0.0,False
16,5ff1e1b60a7214ada100055c,,034100573065,1,29.00,29.00,0.0,870.0,5332f709e4b03c9a25efd0f1,False,...,3,,MILLER LITE 24 PACK,5332f709e4b03c9a25efd0f1,77,False,,0,0.0,False
17,5ff1e1b60a7214ada100055c,,034100573065,1,29.00,29.00,0.0,870.0,5332f709e4b03c9a25efd0f1,False,...,4,,MILLER LITE 24 PACK,5332f709e4b03c9a25efd0f1,77,False,,0,0.0,False
18,5ff1e1b60a7214ada100055c,,034100573065,1,29.00,29.00,0.0,870.0,5332f709e4b03c9a25efd0f1,False,...,5,,MILLER LITE 24 PACK,5332f709e4b03c9a25efd0f1,77,False,,0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6835,602402750a720f05a800016f,,043000048528,1,9.99,9.99,0.0,0.0,,False,...,1,,DUNCAN HINES CAKE MIX,5e825d64f221c312e698a62a,0,False,,1,0.0,False
6836,602402750a720f05a800016f,,043000048528,1,9.99,9.99,0.0,0.0,,False,...,2,,DUNCAN HINES CAKE MIX,5e825d64f221c312e698a62a,0,False,,1,0.0,False
6837,602402750a720f05a800016f,,043000048528,1,9.99,9.99,0.0,0.0,,False,...,3,,DUNCAN HINES CAKE MIX,5e825d64f221c312e698a62a,0,False,,1,0.0,False
6838,602402750a720f05a800016f,,043000048528,1,9.99,9.99,0.0,0.0,,False,...,4,,DUNCAN HINES CAKE MIX,5e825d64f221c312e698a62a,0,False,,1,0.0,False
6839,602402750a720f05a800016f,,043000048528,1,9.99,9.99,0.0,0.0,,False,...,5,,DUNCAN HINES CAKE MIX,5e825d64f221c312e698a62a,0,False,,1,0.0,False

In [35]:
# Identify receipt items where the final price is less than or equal to zero.
receipt_items[(receipt_items["final_price"] <= 0)]

,receipt_id,brand_code,barcode,quantity_purchased,final_price,item_price,price_after_coupon,points_earned,points_payer_id,needs_fetch_review,...,partner_item_id,points_not_awarded_reason,rewards_group,rewards_product_partner_id,target_price,prevent_target_gap_points,competitor_rewards_group,competitive_product,discounted_item_price,deleted
3,5ff1e1f10a720f052300057a,,,0,0.0,0.0,0.0,0.0,,False,...,1,,,,0,True,,0,0.0,False
25,5f9c74f70a7214ad07000037,,,0,0.0,0.0,0.0,0.0,,True,...,2,,,,0,True,,0,0.0,False
26,5f9c74f70a7214ad07000037,,,0,0.0,0.0,0.0,0.0,,True,...,3,,,,0,True,,0,0.0,False
27,5f9c74f70a7214ad07000037,,,0,0.0,0.0,0.0,0.0,,True,...,4,,,,0,True,,0,0.0,False
28,5f9c74f70a7214ad07000037,,,0,0.0,0.0,0.0,0.0,,True,...,5,,,,0,True,,0,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6768,5fb2da580a7214ad89000114,,,0,0.0,0.0,0.0,0.0,,True,...,10,,,,0,True,,0,0.0,False
6769,5fb2da580a7214ad89000114,,,0,0.0,0.0,0.0,0.0,,True,...,11,,,,0,True,,0,0.0,False
6779,601c68b50a720f05f40002c8,,1234,0,0.0,0.0,0.0,0.0,,True,...,2,,,,0,True,,0,0.0,False
6816,602299b40a720f05a80000bc,,1234,0,0.0,0.0,0.0,0.0,,True,...,2,,,,0,True,,0,0.0,False
6845,6025386a0a7214d8e9000241,,1234,0,0.0,0.0,0.0,0.0,,True,...,2,,,,0,True,,0,0.0,False

In [36]:
# Find items where price after coupon is greater than item price
receipt_items[receipt_items["price_after_coupon"] > receipt_items["item_price"]]

Empty DataFrame
Columns: [receipt_id, brand_code, barcode, quantity_purchased, final_price, item_price, price_after_coupon, points_earned, points_payer_id, needs_fetch_review, needs_fetch_review_reason, description, original_receipt_item_text, metabrite_campaign_id, original_meta_brite_barcode, original_meta_brite_description, original_final_price, original_meta_brite_item_price, original_meta_brite_quantity_purchased, user_flagged_barcode, user_flagged_description, user_flagged_new_item, user_flagged_price, user_flagged_quantity, item_number, partner_item_id, points_not_awarded_reason, rewards_group, rewards_product_partner_id, target_price, prevent_target_gap_points, competitor_rewards_group, competitive_product, discounted_item_price, deleted]
Index: []

[0 rows x 35 columns]

In [37]:
# Find items where final price is greater than item price
receipt_items[receipt_items["final_price"] > receipt_items["item_price"]]

Empty DataFrame
Columns: [receipt_id, brand_code, barcode, quantity_purchased, final_price, item_price, price_after_coupon, points_earned, points_payer_id, needs_fetch_review, needs_fetch_review_reason, description, original_receipt_item_text, metabrite_campaign_id, original_meta_brite_barcode, original_meta_brite_description, original_final_price, original_meta_brite_item_price, original_meta_brite_quantity_purchased, user_flagged_barcode, user_flagged_description, user_flagged_new_item, user_flagged_price, user_flagged_quantity, item_number, partner_item_id, points_not_awarded_reason, rewards_group, rewards_product_partner_id, target_price, prevent_target_gap_points, competitor_rewards_group, competitive_product, discounted_item_price, deleted]
Index: []

[0 rows x 35 columns]

In [38]:
# Identify receipt items where the barcode is missing (empty string).
receipt_items[receipt_items["barcode"] == ""]

,receipt_id,brand_code,barcode,quantity_purchased,final_price,item_price,price_after_coupon,points_earned,points_payer_id,needs_fetch_review,...,partner_item_id,points_not_awarded_reason,rewards_group,rewards_product_partner_id,target_price,prevent_target_gap_points,competitor_rewards_group,competitive_product,discounted_item_price,deleted
3,5ff1e1f10a720f052300057a,,,0,0.00,0.00,0.00,0.0,,False,...,1,,,,0,True,,0,0.00,False
8,5ff1e1cd0a720f052300056f,MISSION,,1,2.23,2.23,0.00,0.0,,False,...,1009,,,,0,False,TACO BELL TACO SHELLS,0,2.23,False
25,5f9c74f70a7214ad07000037,,,0,0.00,0.00,0.00,0.0,,True,...,2,,,,0,True,,0,0.00,False
26,5f9c74f70a7214ad07000037,,,0,0.00,0.00,0.00,0.0,,True,...,3,,,,0,True,,0,0.00,False
27,5f9c74f70a7214ad07000037,,,0,0.00,0.00,0.00,0.0,,True,...,4,,,,0,True,,0,0.00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6809,601d7c280a7214ad5900035c,,,1,28.57,28.57,28.57,0.0,,False,...,0,,,,0,False,,0,28.57,False
6810,601d7cd50a7214ad5900069f,,,1,28.57,28.57,28.57,0.0,,False,...,0,,,,0,False,,0,28.57,False
6811,601d7b840a720f055400004e,,,1,28.57,28.57,28.57,0.0,,False,...,0,,,,0,False,,0,28.57,False
6823,602454340a720f05a80001ae,,,1,1.96,1.96,0.00,0.0,,False,...,1008,,,,0,False,,0,1.96,False
6847,602538740a7214d8e9000246,MISSION,,1,2.23,2.23,0.00,0.0,,False,...,1009,,,,0,False,TACO BELL TACO SHELLS,0,2.23,False

In [39]:
import os
import uuid

# Generate UUID function
def generate_uuid():
    return str(uuid.uuid4())

# Add a new UUID column as Primary Key (PK)
receipt_item_data.insert(0, "receipt_item_id", [generate_uuid() for _ in range(len(receipt_item_data))])

# Export cleaned data
output_dir = "/Users/evro/Documents/code/python/fetch/data/validated"
os.makedirs(output_dir, exist_ok=True)

output_file_pkl = os.path.join(output_dir, "receipt_item_data.pkl")
with open(output_file_pkl, "wb") as f:
    pickle.dump(receipt_item_data, f)